/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const table: string;
const themeThinLine: string;
const themeCornerNotch: string;
const themeCellDots: string;
const cellDot: string;

export {
	table,
	themeThinLine,
	themeCornerNotch,
	themeCellDots,
	cellDot
};

export default {
	table,
	themeThinLine,
	themeCornerNotch,
	themeCellDots,
	cellDot
};
