/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const root: string;
const state: string;
const loading: string;
const window: string;
const row: string;
const identity: string;
const cell: string;
const cellValue: string;
const cellLabel: string;

export {
	root,
	state,
	loading,
	window,
	row,
	identity,
	cell,
	cellValue,
	cellLabel
};

export default {
	root,
	state,
	loading,
	window,
	row,
	identity,
	cell,
	cellValue,
	cellLabel
};
