/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const container: string;
const scrollContainer: string;
const content: string;
const window: string;

export {
	container,
	scrollContainer,
	content,
	window
};

export default {
	container,
	scrollContainer,
	content,
	window
};
