/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const outline: string;
const row: string;
const content: string;
const text: string;
const indent: string;
const guidePassThrough: string;
const guidePassThroughEnd: string;
const guideConnector: string;
const guideConnectorLast: string;
const themeWorkflowyClone: string;
const caret: string;
const caretSpacer: string;
const bulletDot: string;
const themeWorkflowyGeometric: string;
const bulletDash: string;
const bulletDashParent: string;
const plusMark: string;
const themeVectorField: string;
const vectorGutter: string;
const vectorSlot: string;
const vectorGutterClickable: string;
const notchTL: string;
const notchBR: string;
const themeCornerNotches: string;
const caretFaint: string;
const caretFaintSpacer: string;
const themeWhitespace: string;

export {
	outline,
	row,
	content,
	text,
	indent,
	guidePassThrough,
	guidePassThroughEnd,
	guideConnector,
	guideConnectorLast,
	themeWorkflowyClone,
	caret,
	caretSpacer,
	bulletDot,
	themeWorkflowyGeometric,
	bulletDash,
	bulletDashParent,
	plusMark,
	themeVectorField,
	vectorGutter,
	vectorSlot,
	vectorGutterClickable,
	notchTL,
	notchBR,
	themeCornerNotches,
	caretFaint,
	caretFaintSpacer,
	themeWhitespace
};

export default {
	outline,
	row,
	content,
	text,
	indent,
	guidePassThrough,
	guidePassThroughEnd,
	guideConnector,
	guideConnectorLast,
	themeWorkflowyClone,
	caret,
	caretSpacer,
	bulletDot,
	themeWorkflowyGeometric,
	bulletDash,
	bulletDashParent,
	plusMark,
	themeVectorField,
	vectorGutter,
	vectorSlot,
	vectorGutterClickable,
	notchTL,
	notchBR,
	themeCornerNotches,
	caretFaint,
	caretFaintSpacer,
	themeWhitespace
};
