/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const prototype: string;
const workspaceLayer: string;
const storyControls: string;
const storyControlsHidden: string;
const tempoButton: string;
const dismissButton: string;
const centeredOverlay: string;
const launcherSurface: string;
const queryRow: string;
const queryInput: string;
const wipeoutQueryInput: string;
const blockCursor: string;
const cursorBlink: string;
const launcherList: string;
const launcherFooter: string;
const origin: string;
const feedback: string;
const keyboardHint: string;
const wipeoutDialog: string;
const wipeoutQuick: string;
const wipeoutDeep: string;
const quickGeometryProbe: string;
const echoes: string;
const echoFrame: string;
const echoDecay: string;

export {
	prototype,
	workspaceLayer,
	storyControls,
	storyControlsHidden,
	tempoButton,
	dismissButton,
	centeredOverlay,
	launcherSurface,
	queryRow,
	queryInput,
	wipeoutQueryInput,
	blockCursor,
	cursorBlink as "cursor-blink",
	launcherList,
	launcherFooter,
	origin,
	feedback,
	keyboardHint,
	wipeoutDialog,
	wipeoutQuick,
	wipeoutDeep,
	quickGeometryProbe,
	echoes,
	echoFrame,
	echoDecay as "echo-decay"
};

export default {
	prototype,
	workspaceLayer,
	storyControls,
	storyControlsHidden,
	tempoButton,
	dismissButton,
	centeredOverlay,
	launcherSurface,
	queryRow,
	queryInput,
	wipeoutQueryInput,
	blockCursor,
	"cursor-blink": cursorBlink,
	launcherList,
	launcherFooter,
	origin,
	feedback,
	keyboardHint,
	wipeoutDialog,
	wipeoutQuick,
	wipeoutDeep,
	quickGeometryProbe,
	echoes,
	echoFrame,
	"echo-decay": echoDecay
};
