/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const dialog: string;
const anchored: string;
const quick: string;
const deep: string;

export {
	dialog,
	anchored,
	quick,
	deep
};

export default {
	dialog,
	anchored,
	quick,
	deep
};
