/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const root: string;
const list: string;
const option: string;
const group: string;
const groupLabel: string;
const groupEmpty: string;
const copy: string;
const mark: string;
const label: string;
const description: string;
const reason: string;
const meta: string;
const empty: string;
const status: string;

export {
	root,
	list,
	option,
	group,
	groupLabel,
	groupEmpty,
	copy,
	mark,
	label,
	description,
	reason,
	meta,
	empty,
	status
};

export default {
	root,
	list,
	option,
	group,
	groupLabel,
	groupEmpty,
	copy,
	mark,
	label,
	description,
	reason,
	meta,
	empty,
	status
};
