/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const storyFrame: string;
const anchoredFrame: string;
const reopen: string;
const invoker: string;
const quickContent: string;
const deepContent: string;
const header: string;
const feedback: string;
const listHarness: string;
const narrowFrame: string;
const themeMatrix: string;
const themeCell: string;
const reducedMotion: string;

export {
	storyFrame,
	anchoredFrame,
	reopen,
	invoker,
	quickContent,
	deepContent,
	header,
	feedback,
	listHarness,
	narrowFrame,
	themeMatrix,
	themeCell,
	reducedMotion
};

export default {
	storyFrame,
	anchoredFrame,
	reopen,
	invoker,
	quickContent,
	deepContent,
	header,
	feedback,
	listHarness,
	narrowFrame,
	themeMatrix,
	themeCell,
	reducedMotion
};
