/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const formulaInput: string;
const tokenDisplay: string;
const textSegment: string;
const refToken: string;
const refTokenRemove: string;
const inputRow: string;
const rawInput: string;
const columnPickerBtn: string;
const autocomplete: string;
const autocompleteItem: string;
const autocompleteItemSelected: string;
const autocompleteColName: string;
const autocompleteColType: string;

export {
	formulaInput,
	tokenDisplay,
	textSegment,
	refToken,
	refTokenRemove,
	inputRow,
	rawInput,
	columnPickerBtn,
	autocomplete,
	autocompleteItem,
	autocompleteItemSelected,
	autocompleteColName,
	autocompleteColType
};

export default {
	formulaInput,
	tokenDisplay,
	textSegment,
	refToken,
	refTokenRemove,
	inputRow,
	rawInput,
	columnPickerBtn,
	autocomplete,
	autocompleteItem,
	autocompleteItemSelected,
	autocompleteColName,
	autocompleteColType
};
