/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const tableFace: string;
const toolbar: string;
const filterTag: string;
const addFilterBtn: string;
const filterPopover: string;
const tableContainer: string;
const table: string;
const th: string;
const thContent: string;
const sortIndicator: string;
const typeLabel: string;
const thAddColumn: string;
const addColumnBtn: string;
const thInput: string;
const contextMenu: string;
const contextMenuItem: string;
const contextMenuSub: string;
const contextMenuDanger: string;
const td: string;
const cell: string;
const cellSelected: string;
const cellEditing: string;
const cellNumber: string;
const cellBoolean: string;
const cellDate: string;
const cellSelect: string;
const badge: string;
const coercionError: string;
const thRowId: string;
const rowIdCell: string;
const addRowTr: string;
const addRowBtn: string;
const typePicker: string;
const typePickerItem: string;
const typePickerIcon: string;
const dragging: string;
const dropTarget: string;

export {
	tableFace,
	toolbar,
	filterTag,
	addFilterBtn,
	filterPopover,
	tableContainer,
	table,
	th,
	thContent,
	sortIndicator,
	typeLabel,
	thAddColumn,
	addColumnBtn,
	thInput,
	contextMenu,
	contextMenuItem,
	contextMenuSub,
	contextMenuDanger,
	td,
	cell,
	cellSelected,
	cellEditing,
	cellNumber,
	cellBoolean,
	cellDate,
	cellSelect,
	badge,
	coercionError,
	thRowId,
	rowIdCell,
	addRowTr,
	addRowBtn,
	typePicker,
	typePickerItem,
	typePickerIcon,
	dragging,
	dropTarget
};

export default {
	tableFace,
	toolbar,
	filterTag,
	addFilterBtn,
	filterPopover,
	tableContainer,
	table,
	th,
	thContent,
	sortIndicator,
	typeLabel,
	thAddColumn,
	addColumnBtn,
	thInput,
	contextMenu,
	contextMenuItem,
	contextMenuSub,
	contextMenuDanger,
	td,
	cell,
	cellSelected,
	cellEditing,
	cellNumber,
	cellBoolean,
	cellDate,
	cellSelect,
	badge,
	coercionError,
	thRowId,
	rowIdCell,
	addRowTr,
	addRowBtn,
	typePicker,
	typePickerItem,
	typePickerIcon,
	dragging,
	dropTarget
};
