/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const btn: string;
const primary: string;
const secondary: string;
const ghost: string;
const destructive: string;
const icon: string;

export {
	btn,
	primary,
	secondary,
	ghost,
	destructive,
	icon
};

export default {
	btn,
	primary,
	secondary,
	ghost,
	destructive,
	icon
};
