/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const menu: string;
const item: string;
const muted: string;
const shortcut: string;
const separator: string;

export {
	menu,
	item,
	muted,
	shortcut,
	separator
};

export default {
	menu,
	item,
	muted,
	shortcut,
	separator
};
