/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const divider: string;
const short: string;
const full: string;

export {
	divider,
	short,
	full
};

export default {
	divider,
	short,
	full
};
