/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const container: string;
const row: string;
const col1: string;
const col2: string;
const col3: string;
const col4: string;
const col5: string;
const col6: string;
const col7: string;
const col8: string;
const col9: string;
const col10: string;
const col11: string;
const col12: string;
const col13: string;
const col14: string;
const col15: string;
const col16: string;
const sm1: string;
const sm2: string;
const sm3: string;
const sm4: string;
const sm5: string;
const sm6: string;
const sm7: string;
const sm8: string;
const md1: string;
const md2: string;
const md3: string;
const md4: string;
const md5: string;
const md6: string;
const md7: string;
const md8: string;
const md9: string;
const md10: string;
const md11: string;
const md12: string;

export {
	container,
	row,
	col1 as "col-1",
	col2 as "col-2",
	col3 as "col-3",
	col4 as "col-4",
	col5 as "col-5",
	col6 as "col-6",
	col7 as "col-7",
	col8 as "col-8",
	col9 as "col-9",
	col10 as "col-10",
	col11 as "col-11",
	col12 as "col-12",
	col13 as "col-13",
	col14 as "col-14",
	col15 as "col-15",
	col16 as "col-16",
	sm1 as "sm-1",
	sm2 as "sm-2",
	sm3 as "sm-3",
	sm4 as "sm-4",
	sm5 as "sm-5",
	sm6 as "sm-6",
	sm7 as "sm-7",
	sm8 as "sm-8",
	md1 as "md-1",
	md2 as "md-2",
	md3 as "md-3",
	md4 as "md-4",
	md5 as "md-5",
	md6 as "md-6",
	md7 as "md-7",
	md8 as "md-8",
	md9 as "md-9",
	md10 as "md-10",
	md11 as "md-11",
	md12 as "md-12"
};

export default {
	container,
	row,
	"col-1": col1,
	"col-2": col2,
	"col-3": col3,
	"col-4": col4,
	"col-5": col5,
	"col-6": col6,
	"col-7": col7,
	"col-8": col8,
	"col-9": col9,
	"col-10": col10,
	"col-11": col11,
	"col-12": col12,
	"col-13": col13,
	"col-14": col14,
	"col-15": col15,
	"col-16": col16,
	"sm-1": sm1,
	"sm-2": sm2,
	"sm-3": sm3,
	"sm-4": sm4,
	"sm-5": sm5,
	"sm-6": sm6,
	"sm-7": sm7,
	"sm-8": sm8,
	"md-1": md1,
	"md-2": md2,
	"md-3": md3,
	"md-4": md4,
	"md-5": md5,
	"md-6": md6,
	"md-7": md7,
	"md-8": md8,
	"md-9": md9,
	"md-10": md10,
	"md-11": md11,
	"md-12": md12
};
