/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const heading: string;
const sm: string;
const md: string;
const lg: string;

export {
	heading,
	sm,
	md,
	lg
};

export default {
	heading,
	sm,
	md,
	lg
};
