/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const bar: string;
const tab: string;
const active: string;

export {
	bar,
	tab,
	active
};

export default {
	bar,
	tab,
	active
};
