/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const container: string;
const scrollContainer: string
const content: string
const item: string
const itemContent: string
const red: string
const window: string

export { container, scrollContainer, content, item, itemContent, red, window }

export default {
  container,
  scrollContainer,
  content,
  item,
  itemContent,
  red,
  window,
}
