/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const container: string;
const scrollContainer: string;
const content: string;
const item: string;
const itemContent: string;
const itemId: string;
const itemHeight: string;
const red: string;
const window: string;
const windowInfo: string;

export {
	container,
	scrollContainer,
	content,
	item,
	itemContent,
	itemId,
	itemHeight,
	red,
	window,
	windowInfo
};

export default {
	container,
	scrollContainer,
	content,
	item,
	itemContent,
	itemId,
	itemHeight,
	red,
	window,
	windowInfo
};
